apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.proftpd.service.name }}
  labels:
    app: {{ .Release.Name }}-proftpd 
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 22
      {{ if not .Values.use_ingress }}
      nodePort: {{.Values.proftpd.node_port_exposed}}
      {{ end }}
      protocol: TCP
      name: sftp
  selector:
    app: {{ .Release.Name }}-proftpd
    release: {{ .Release.Name }}
