apiVersion: v1
kind: Service
metadata:
  name: galaxy-svc-k8s
  labels:
    app: {{.Values.galaxy_label_app}}
spec:
  type: NodePort
  ports:
   - name: http 
     port: {{.Values.galaxy_internal_port}}
     nodePort: {{.Values.galaxy_node_port_exposed}}
  selector:
    app: {{.Values.galaxy_metadata_name}}
