apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "galaxy.fullname" . }}-config-map
  labels:
    app: {{ template "galaxy.name" . }}
    chart: {{ template "galaxy.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- range $key, $entry := .Values.configs -}}
  {{- if $entry.contents -}}
  {{- $key | nindent 2 }}: |
    {{- tpl ($entry.contents | toYaml | replace "{{\n" "{{" | replace "|" "") $ | nindent 4 -}}
    {{- end }}
  {{- end }}
