apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "galaxy.fullname" . }}-config-map
  labels:
    app.kubernetes.io/name: {{ include "galaxy.name" . }}
    helm.sh/chart: {{ include "galaxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  {{- range $key, $entry := .Values.configs -}}
  {{- if $entry.contents -}}
  {{- $key | nindent 2 }}: |
    {{- tpl ($entry.contents | toYaml | replace "{{\n" "{{" | replace "\n    }}" " }}" | replace "|" "") $ | nindent 4 -}}
    {{- end }}
  {{- end }}
