{{- $fullName := include "galaxy.fullname" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-config-map
  labels:
    app: {{ template "galaxy.name" . }}
    chart: {{ template "galaxy.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- range $key, $entry := .Values.configs }}
  {{ $key }}: |
    {{- if $entry.contents -}}
    {{ tpl ($entry.contents | toYaml | replace "{{\n" "{{" | replace "|" "") $ | nindent 4 }}
    {{- end }}
  {{- end }}
