{{ if .Values.persistence.pv.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-{{ .Values.persistence.pv.name }}
  labels:
    app.kubernetes.io/name: {{ include "galaxy.name" . }}
    helm.sh/chart: {{ include "galaxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  storageClassName: "{{ .Values.persistence.storageClass }}"
  capacity:
    storage: {{ .Values.persistence.size | quote }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  hostPath:
    # This is a host specific path where Galaxy files will be placed.
    path: "{{ .Values.persistence.pv.hostPath }}"
    type: DirectoryOrCreate
{{ end }}

---

{{ if .Values.postgresql.persistence.pv.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-{{ .Values.postgresql.persistence.pv.name }}
  labels:
    app.kubernetes.io/name: {{ include "galaxy.name" . }}
    helm.sh/chart: {{ include "galaxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  storageClassName: "{{ .Values.postgresql.persistence.storageClass }}"
  capacity:
    storage: {{ .Values.postgresql.persistence.size | quote }}
  accessModes:
    - {{ .Values.postgresql.persistence.accessMode }}
  hostPath:
    # This is a host specific path where Galaxy files will be placed.
    path: "{{ .Values.postgresql.persistence.pv.hostPath }}"
    type: DirectoryOrCreate
{{ end }}

---

{{ if .Values.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-{{ .Values.persistence.name }}
  labels:
    app.kubernetes.io/name: {{ include "galaxy.name" . }}
    helm.sh/chart: {{ include "galaxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- if .Values.persistence.annotations }}
  annotations:
{{ toYaml .Values.persistence.annotations | indent 4 }}
{{- end }}
spec:
  {{- if .Values.persistence.storageClass }}
  {{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
  {{- end }}
  {{- end }}
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{ end }}
---

{{ if .Values.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-{{ .Values.postgresql.persistence.pv.name }}-claim
  labels:
    app.kubernetes.io/name: {{ include "galaxy.name" . }}
    helm.sh/chart: {{ include "galaxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- if .Values.postgresql.persistence.annotations }}
  annotations:
{{ toYaml .Values.postgresql.persistence.annotations | indent 4 }}
{{- end }}
spec:
  {{- if .Values.postgresql.persistence.storageClass }}
  {{- if (eq "-" .Values.postgresql.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.postgresql.persistence.storageClass }}"
  {{- end }}
  {{- end }}
  accessModes:
    - {{ .Values.postgresql.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.postgresql.persistence.size | quote }}
{{ end }}
