{{ if .Values.persistence.pv.enabled }}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .Values.persistence.pv.name }}
  labels:
    app: {{ template "galaxy.name" . }}
    chart: {{ template "galaxy.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.persistence.size | quote }}
  accessModes:
    - ReadWriteMany
  hostPath:
    # This is a host specific path where Galaxy files will be placed.
    path: "{{ .Values.persistence.pv.hostPath }}"
{{ end }}

---

{{- if and .Values.persistence.enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.persistence.name }}
  labels:
    app: {{ template "galaxy.name" . }}
    chart: {{ template "galaxy.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.persistence.annotations }}
  annotations:
{{ toYaml .Values.persistence.annotations | indent 4 }}
{{- end }}
spec:
  {{- if .Values.persistence.storageClass }}
  {{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
  {{- end }}
  {{- end }}
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{ end }}