{{- if .Values.cvmfs.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "galaxy.fullname" . }}-cvmfs-gxy-main-pvc
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: {{ .Values.cvmfs.main.pvc.storage }}
  storageClassName: cvmfs-gxy-main
{{- end }}
