{{- if (include "galaxy.createGalaxyDbSecret" .) }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}-galaxy-db-password
  labels:
    app.kubernetes.io/name: {{ include "galaxy.name" . }}
    helm.sh/chart: {{ include "galaxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  galaxy-db-password: {{ include "galaxy.galaxyDbPassword" . | b64enc | quote }}
{{- end }}
