{{ if .Values.rabbitmq.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-rabbitmq-load-definitions
type: Opaque
stringData:
  load_definitions.json: |
    {
       "vhosts": [
         {
           "name": "galaxy"
         }
        ],
       "permissions": [
         {
           "user": "{{ .Values.rabbitmq.auth.username }}",
           "vhost": "galaxy",
           "configure": ".*",
           "write": ".*",
           "read": ".*"
         }
        ]
    }
{{ end }}
