## Here, helm keeps track of what dependencies that are required for the
## application. Dependencies should be listed here, then the dependencies
## updated with:
##
##    helm dep update
##
## and the requirements.lock file commited.
dependencies:
    - name: postgresql
      repository: https://kubernetes-charts.storage.googleapis.com/
      version: 3.14.2
      condition: postgresql.enabled
