{{- $fullName := include "galaxy.fullname" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-config-map
  labels:
    app: {{ template "galaxy.name" . }}
    chart: {{ template "galaxy.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
    job_conf.xml: |
      <job_conf>
          <plugins>
              <plugin id="local" type="runner" load="galaxy.jobs.runners.local:LocalJobRunner" workers="4"/>
          </plugins>
          <handlers assign_with="db-skip-locked" />
          <destinations>
              <destination id="local" runner="local"/>
          </destinations>
      </job_conf>
