kind: PersistentVolume
apiVersion: v1
metadata:
  name: galaxy-pv
  labels:
    app: galaxy
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/tmp/k8s/volumes/galaxy/data"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: galaxy-pvc
  labels:
    app: galaxy
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
